def add_payment(
    payments_facade_domain,
    with_synced_sessionlocal,
    payments_domain,
    invalidate_after_write,
    invalidate_data_cache_fn,
    *,
    booking_id,
    amount,
    bride_name,
    groom_name,
    notes,
    date_val,
    session,
    commit,
    money_fn,
    money_float_fn,
    msg_invalid_value,
    msg_payment_gt_remaining,
):
    return payments_facade_domain.add_payment(
        with_synced_sessionlocal,
        payments_domain,
        invalidate_after_write,
        invalidate_data_cache_fn,
        booking_id=booking_id,
        amount=amount,
        bride_name=bride_name,
        groom_name=groom_name,
        notes=notes,
        date_val=date_val,
        session=session,
        commit=commit,
        money_fn=money_fn,
        money_float_fn=money_float_fn,
        msg_invalid_value=msg_invalid_value,
        msg_payment_gt_remaining=msg_payment_gt_remaining,
    )


def update_payment(
    payments_facade_domain,
    with_synced_sessionlocal,
    payments_domain,
    invalidate_after_write,
    invalidate_data_cache_fn,
    *,
    p_id,
    booking_id,
    amount,
    notes,
    date_val,
    money_fn,
    money_float_fn,
    msg_invalid_value,
    msg_payment_gt_remaining,
):
    return payments_facade_domain.update_payment(
        with_synced_sessionlocal,
        payments_domain,
        invalidate_after_write,
        invalidate_data_cache_fn,
        p_id=p_id,
        booking_id=booking_id,
        amount=amount,
        notes=notes,
        date_val=date_val,
        money_fn=money_fn,
        money_float_fn=money_float_fn,
        msg_invalid_value=msg_invalid_value,
        msg_payment_gt_remaining=msg_payment_gt_remaining,
    )


def delete_payment(
    payments_facade_domain,
    with_synced_sessionlocal,
    payments_domain,
    invalidate_after_write,
    invalidate_data_cache_fn,
    *,
    p_id,
    money_fn,
    money_float_fn,
):
    return payments_facade_domain.delete_payment(
        with_synced_sessionlocal,
        payments_domain,
        invalidate_after_write,
        invalidate_data_cache_fn,
        p_id=p_id,
        money_fn=money_fn,
        money_float_fn=money_float_fn,
    )
