def add_customer(
    customers_facade_domain,
    with_synced_sessionlocal,
    customers_domain,
    invalidate_after_write,
    *,
    name,
    groom,
    phone1,
    phone2,
    address,
    reg_date,
    notes,
    msg_missing_info,
    msg_invalid_phone,
    msg_added,
):
    return customers_facade_domain.add_customer(
        with_synced_sessionlocal,
        customers_domain,
        invalidate_after_write,
        name=name,
        groom=groom,
        phone1=phone1,
        phone2=phone2,
        address=address,
        reg_date=reg_date,
        notes=notes,
        msg_missing_info=msg_missing_info,
        msg_invalid_phone=msg_invalid_phone,
        msg_added=msg_added,
    )


def update_customer(
    customers_facade_domain,
    with_synced_sessionlocal,
    customers_domain,
    invalidate_after_write,
    invalidate_data_cache_fn,
    *,
    c_id,
    name,
    groom,
    phone1,
    phone2,
    address,
    reg_date,
    notes,
    msg_missing_info,
    msg_not_found,
    msg_phone_used_by_another,
    msg_updated,
):
    return customers_facade_domain.update_customer(
        with_synced_sessionlocal,
        customers_domain,
        invalidate_after_write,
        invalidate_data_cache_fn,
        c_id=c_id,
        name=name,
        groom=groom,
        phone1=phone1,
        phone2=phone2,
        address=address,
        reg_date=reg_date,
        notes=notes,
        msg_missing_info=msg_missing_info,
        msg_not_found=msg_not_found,
        msg_phone_used_by_another=msg_phone_used_by_another,
        msg_updated=msg_updated,
    )


def delete_customer(
    customers_facade_domain,
    with_synced_sessionlocal,
    customers_domain,
    invalidate_after_write,
    invalidate_data_cache_fn,
    *,
    c_id,
    msg_not_found,
    msg_has_bookings,
    msg_deleted,
):
    return customers_facade_domain.delete_customer(
        with_synced_sessionlocal,
        customers_domain,
        invalidate_after_write,
        invalidate_data_cache_fn,
        c_id=c_id,
        msg_not_found=msg_not_found,
        msg_has_bookings=msg_has_bookings,
        msg_deleted=msg_deleted,
    )
